export function TableIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width="24"
      height="24"
      fill="var(--current-on-color)"
    >
      <rect
        x="3"
        y="3"
        width="18"
        height="18"
        rx="2"
        ry="2"
        stroke="var(--current-on-color)"
        strokeWidth="2"
        fill="none"
      />
      <rect x="3" y="3" width="18" height="6" fill="var(--current-on-color)" />
      <line
        x1="3"
        y1="9"
        x2="21"
        y2="9"
        stroke="var(--current-on-color)"
        strokeWidth="2"
      />
      <line
        x1="3"
        y1="15"
        x2="21"
        y2="15"
        stroke="var(--current-on-color)"
        strokeWidth="2"
      />
      <line
        x1="9"
        y1="9"
        x2="9"
        y2="21"
        stroke="var(--current-on-color)"
        strokeWidth="2"
      />
      <line
        x1="15"
        y1="9"
        x2="15"
        y2="21"
        stroke="var(--current-on-color)"
        strokeWidth="2"
      />
    </svg>
  );
}
